name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@main
#     - name: Build
#       run: xcodebuild build -scheme CashAppStocks
    - name: Run tests
      run: xcodebuild test -scheme CashAppStocksTests
